version: "2"

services:
  http:
    image: merrettr/circletest-http
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: circletest-http
    ports:
      - 8888:80
    links:
      - app
    volumes_from:
      - app

  app:
    image: merrettr/circletest-app
    container_name: circletest-app
    build: .
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
    environment:
      ENV_VAR: dev
