version: "2"

services:
  http:
    image: docker.merrett.io:5000/merrettr/circletest-http
    container_name: circletest-http
    ports:
      - 8888:80
    links:
      - app
    volumes_from:
      - app

  app:
    image: docker.merrett.io:5000/merrettr/circletest-app
    container_name: circletest-app
    expose:
      - 9000
    environment:
      ENV_VAR: ${ENV_LINE}
